name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
          echo ::set-output name=sha::$(echo ${GITHUB_SHA})
        id: vars
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: tikarya
          password: docker-hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tikarya/eth-statediff-service:${{ steps.vars.outputs.tag }}
          build-args: |
            GIT_COMMIT=${{ steps.vars.outputs.sha }}